### PR TITLE
Use family name instead of font name when requesting data.

### PR DESCRIPTION
**Pull request by garretrieger**
This allows the font name to be varied per weight.

### CODE REVIEW

**Comment by bstell** [comment]
Just to be clear, do you mean?

* This allows the **path to share the familyName and only** the font **file**name **needs** to be varied per weight

**Comment by garretrieger** [comment]
Font info passed in looks like this with multiple weights:

'Noto Sans Japanese', ..., {name: 'notosansjapanese100', weight: 100, version: 'v3', fontkit: '3fHSXQ1q-wbTrz6G1O8VOiHWie5YszDE-r2ScC861uk'}

When I say font name, I'm referring to the "name" parameter above.  It's used as the CSS class name for the font and the idb name.  So with this change use family name, 'Noto Sans Japanese', to generate the url's and 'notosansjapanese100' for everything else.

**Comment by bstell** [comment]
The meaning of fontInfo needs to be clearer (mea culpa).

Would you kindly add this info to the JsDoc?

**Comment by garretrieger** [comment]
Updated the jsdoc with more info on fontInfo.

**Pull request merged**
